name: Playwright Tests
on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]
jobs:
  test:
    timeout-minutes: 60
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - uses: actions/setup-node@v4
      with:
        node-version: lts/*
        
    - name: Build Docker image
      run: |
        echo "FROM node:20-bookworm" > Dockerfile
        echo "WORKDIR /app" >> Dockerfile
        echo "COPY . ." >> Dockerfile
        echo "RUN npm install" >> Dockerfile
        echo "RUN npx playwright install" >> Dockerfile
        echo "RUN npx playwright install-deps" >> Dockerfile
        echo "RUN npx --yes create-sitecore-jss --templates nextjs,nextjs-styleguide --fetchWith REST --destination sample/nextjs-app --yes" >> Dockerfile
        echo "WORKDIR /app/sample/nextjs-app" >> Dockerfile
        echo "CMD [\"npm\", \"run\", \"start\"]" >> Dockerfile
        docker build -t nextjs-app .

    - name: Run Docker container
      run: |
        docker run -d -p 3000:3000 --name nextjs-app nextjs-app
        sleep 120
    
    - name: Verify Docker container is running
      run: |
        if [ "$(docker inspect -f '{{.State.Running}}' nextjs-app)" != "true" ]; then
          echo "Docker container is not running."
          exit 1
        fi
        echo "Docker container is running."

    - name: Run tests inside Docker container
      run: |
        docker exec nextjs-app sh -c "cd /app && npm install && npx playwright test"

    - uses: actions/upload-artifact@v4
      if: ${{ !cancelled() }}
      with:
        name: playwright-report
        path: playwright-report/
        retention-days: 30
