name: Run Test - Docker
on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]
jobs:
  test:
    timeout-minutes: 60
    runs-on: windows-2019
    steps:
    - uses: actions/checkout@v4
    - uses: actions/setup-node@v4
      with:
        node-version: lts/*
        
    - name: Build Docker JSS Image
      run: |
        echo "FROM stefanscherer/node-windows:latest" > Dockerfile
        echo "WORKDIR /app" >> Dockerfile
        echo "RUN npx --yes create-sitecore-jss --templates nextjs,nextjs-styleguide --fetchWith REST --destination sample/nextjs-app --yes" >> Dockerfile
        echo "WORKDIR /app/sample/nextjs-app" >> Dockerfile
        echo "RUN ls -la /app/sample/nextjs-app" >> Dockerfile
        echo "CMD [\"npm\", \"run\", \"start\"]" >> Dockerfile
        docker build -t nextjs-app .

    - name: Run Docker container
      run: |
        docker run -d -p 3000:3000 --name nextjs-app nextjs-app
        sleep 120

    - name: Print Docker logs
      run: |
        docker logs nextjs-app
    
    - name: Verify Docker container is running
      run: |
        if [ "$(docker inspect -f '{{.State.Running}}' nextjs-app)" != "true" ]; then
          echo "Docker container is not running."
          exit 1
        fi
        echo "Docker container is running."

    - name: Install playwright dependencies
      run: npm ci

    - name: Install Playwright Browsers
      run: npx playwright install --with-deps

    - name: Run Playwright Tests
      run: npx playwright test

    - uses: actions/upload-artifact@v4
      if: ${{ !cancelled() }}
      with:
        name: playwright-report
        path: playwright-report/
        retention-days: 30
